---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web
  namespace: test
spec:
  selector:
    matchLabels:
      name: test-web
  replicas: 1
  strategy:
    type: Recreate #RollingUpdate #Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: test-web
    spec:
      containers:
      - name: test-web
        image: docker.io/lenacloud/lena-web:1.3.1.1-centos7-jdk8-openjdk
        imagePullPolicy: Always
        #livenessProbe:
        #  httpGet:
        #    path: /index.html
        #    port: 7180
        #  initialDelaySeconds: 20
        #  periodSeconds: 5
        #readinessProbe:
        #  httpGet:
        #    path: /index.html
        #    port: 7180
        #  initialDelaySeconds: 5
        #  periodSeconds: 3
        ports:
        - containerPort: 7180
        envFrom:
        - configMapRef:
            name: test-web
        volumeMounts:
        - name: docs
          mountPath: /sorc001/htdocs
        - name: logs
          mountPath: /usr/local/lenaw/servers/webServer/logs
        #env:
        #- name: NODE_IP
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: status.hostIP
        #- name: NODE_NAME
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: spec.nodeName          
      volumes:
        - name: docs
          nfs:
            server: fs-d0a8a7b1.efs.ap-northeast-2.amazonaws.com
            path: /test-doc/htdocs
        - name: logs
          nfs:
            server: fs-d0a8a7b1.efs.ap-northeast-2.amazonaws.com
            path: /test-log
      terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-web
  namespace: test
data:
  LENA_MANAGER_ADDRESS: "[manager address1]"
  LENA_MANAGER_MONITORING_PORT: "16100"
  LENA_MANAGER_KEY: "[manager key 1 ]"
  #LENA_MANAGER_2ND_ADDRESS: "[manager address2]"  
  #LENA_MANAGER_2ND_UDP: "16100"
  #LENA_MANAGER_2ND_KEY: "[manager key 2]"  
  LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
  LENA_CONFIG_TEMPLATE_ID: "test-web"
  LENA_LICENSE_DOWNLOAD_URL: "manager"
  LENA_CONTRACT_CODE: "[Contract code from LENA]"
  LENA_AGENT_RUN: "Y"
#  LENA_USER: "lena"
  LENA_SERVICE_PORT: "7180"
  LENA_LOG_OUTPUT_DIR: "/usr/local/lenaw/servers/webServer/logs/`hostname`/"  
  #LENA_LOG_OUTPUT_DIR: "/usr/local/lenaw/servers/webServer/logs/`hostname`/$NODE_IP"
